# Server Configuration
server.port=${PORT:8080}
server.servlet.context-path=/

# Application Name
spring.application.name=trial-app-backend

# Logging Level
logging.level.root=INFO
logging.level.com.example.trialapp=DEBUG

# Server shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
